Working
BSGreaves/relationship-selector pull request #1
Opened 2017-01-22 23:05 UTC by BSGreaves

2017-01-28 19:42 UTC, BSGreaves commented
@drdreed This one's ready too.
It's a little nasty to "grade" because of all the steps we had to do. Sorry.

2017-02-04 15:13 UTC, DevDreed requested changes

2017-02-04 15:13 UTC, drdreed commented on index.html
> +<!doctype html>
<!DOCTYPE html> should be like this.

2017-02-04 15:13 UTC, drdreed commented on index.html
> +<!doctype html>
`<!DOCTYPE html>`

2017-02-08 01:16 UTC, morecallan commented
@BSGreaves nice catch by drdreed but no need to change this for this exercise. technically the tag is case insensitive, it just shows in caps to emphasize importance

2017-02-08 03:07 UTC, merged